<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Authors>Izumi</Authors>
    <Version>2.0.4</Version>
    <AssemblyName>Gallery</AssemblyName>
    <RootNamespace>Gallery</RootNamespace>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" Exclude="Assets\Fonts\**;Assets\Locale\**"/>
<!--    <AvaloniaResource Include="Assets\**" Exclude="Assets\Locale\**"/>-->
    
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
<!--    <PackageReference Include="Avalonia.Diagnostics">-->
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../src/AvaloniaFluentUI/AvaloniaFluentUI.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Pages\StatusAndInformationPage\ToolTipPage.axaml.cs">
      <DependentUpon>ToolTipPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\StatusAndInformationPage\InformationPage.axaml.cs">
      <DependentUpon>InfoBadge.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\StatusAndInformationPage\InfoBarPage.axaml.cs">
      <DependentUpon>InfoBarPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\StatusAndInformationPage\ProgressPage.axaml.cs">
      <DependentUpon>ProgressPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPage.axaml.cs">
      <DependentUpon>WizardPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPages\P1.axaml.cs">
      <DependentUpon>P1.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPages\P2.axaml.cs">
      <DependentUpon>P2.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPages\P3.axaml.cs">
      <DependentUpon>P3.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPages\P4.axaml.cs">
      <DependentUpon>P4.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\WizardPages\P5.axaml.cs">
      <DependentUpon>P5.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\SettingCardPage.axaml.cs">
      <DependentUpon>SettingCardPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MediaView.axaml.cs">
      <DependentUpon>MediaView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\DialogAndPopupPage\PopupDrawerPage.axaml.cs">
      <DependentUpon>PopupDrawerPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Pages\ViewPage\TimeLinePage.axaml.cs">
      <DependentUpon>TimeLinePage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
